### Send GET request to query every boardgames
GET http://localhost:3000/api/boardgames


### Send POST request with json body
POST http://localhost:3000/api/boardgames
Content-Type: application/json

{
  "owner": "Oscar",
  "bggUrl": "http://testurl",
  "lentTo": "Axelle",
  "name": "Le jeu 1"
}