### Send GET request to query every boardgames
GET http://localhost:3000/api/boardgames


### Send POST request with json body
POST http://localhost:3000/api/boardgames
Content-Type: application/json

{
  "owner": "Jeb",
  "bgg_url": "http://testurl",
  "lent_to": "Dude",
  "name": "Foo bar"
}