version: '3.3'
services:
  app:
    ports:
      - '80:8080'
    volumes:
      - 'db:/usr/src/app/databases'
    restart: always
    logging:
      options:
        max-size: 1g
    image: eht-boardgame-manager
volumes:
  db: